// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AstoundSports.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20220406192914_DatabaseCreation")]
    partial class DatabaseCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Models.Athlete", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AthleteId");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaximumCalories")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Athletes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2e235ac6-a3aa-40a4-a5eb-38a36afe4378"),
                            Age = 35,
                            Country = "BR",
                            MaximumCalories = 100,
                            Name = "Audrey ",
                            SurName = "Hughes"
                        },
                        new
                        {
                            Id = new Guid("22ab4e05-4acd-4235-9b99-1d012cd06bb4"),
                            Age = 20,
                            Country = "CO",
                            MaximumCalories = 250,
                            Name = "Sue ",
                            SurName = "Sharp"
                        },
                        new
                        {
                            Id = new Guid("74c00bd6-e657-49af-ae43-59bfc10c446b"),
                            Age = 40,
                            Country = "BR",
                            MaximumCalories = 80,
                            Name = "Joseph ",
                            SurName = "Sutherland"
                        });
                });

            modelBuilder.Entity("Entities.Models.Sport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SportId");

                    b.Property<int>("CaloriesBurntByMinute")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfPlayers")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sports");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c6c273b0-0ee3-4fd3-aa07-d1c781df1c61"),
                            CaloriesBurntByMinute = 10,
                            Duration = 90,
                            Name = "Soccer",
                            NumberOfPlayers = 24
                        },
                        new
                        {
                            Id = new Guid("56e8d823-f384-4005-a4ed-27c4d0156fc0"),
                            CaloriesBurntByMinute = 10,
                            Duration = 48,
                            Name = "Basket",
                            NumberOfPlayers = 10
                        },
                        new
                        {
                            Id = new Guid("998c6595-5bd1-45c4-b271-83a840b3b656"),
                            CaloriesBurntByMinute = 15,
                            Duration = 30,
                            Name = "Table Tenis",
                            NumberOfPlayers = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
