// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

namespace Repository.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20220407001958_DatabaseCreation")]
    partial class DatabaseCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Models.Athlete", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AthleteId");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaximumCalories")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Athletes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f049f5a6-e1f4-4300-8f54-a44b63831a37"),
                            Age = 35,
                            Country = "BR",
                            MaximumCalories = 1000,
                            Name = "Audrey",
                            SurName = "Hughes"
                        },
                        new
                        {
                            Id = new Guid("1fdba9a7-58fa-4df3-87ec-59acaa2bcb55"),
                            Age = 20,
                            Country = "CO",
                            MaximumCalories = 2500,
                            Name = "Sue",
                            SurName = "Sharp"
                        },
                        new
                        {
                            Id = new Guid("11aa2e81-501e-46f4-a174-6c3dda4a9028"),
                            Age = 40,
                            Country = "BR",
                            MaximumCalories = 800,
                            Name = "Joseph",
                            SurName = "Sutherland"
                        });
                });

            modelBuilder.Entity("Entities.Models.Sport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SportId");

                    b.Property<int>("CaloriesBurntByMinute")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfPlayers")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sports");

                    b.HasData(
                        new
                        {
                            Id = new Guid("69078b9a-eef0-4161-aeca-097056af10bf"),
                            CaloriesBurntByMinute = 10,
                            Duration = 90,
                            Name = "Soccer",
                            NumberOfPlayers = 24
                        },
                        new
                        {
                            Id = new Guid("30f37dc3-6e2b-4b78-a172-a553d28a43ac"),
                            CaloriesBurntByMinute = 10,
                            Duration = 48,
                            Name = "Basket",
                            NumberOfPlayers = 10
                        },
                        new
                        {
                            Id = new Guid("781f2e75-99bf-4b4a-847a-719f03a495bf"),
                            CaloriesBurntByMinute = 15,
                            Duration = 30,
                            Name = "Table Tenis",
                            NumberOfPlayers = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
